INSERT INTO customer_info (name,age) VALUES ('Nethaniah',10);
INSERT INTO customer_info (name,age) VALUES ('Batsheva',15);
INSERT INTO customer_info (name,age) VALUES ('Eliezer',20);
INSERT INTO customer_info (name,age) VALUES ('Achaikos',22);
INSERT INTO customer_info (name,age) VALUES ('Shem',18);
INSERT INTO customer_info (name,age) VALUES ('Nathaniel',14);
INSERT INTO customer_info (name,age) VALUES ('Jase',16);
INSERT INTO customer_info (name,age) VALUES ('Jesse',35);
INSERT INTO customer_info (name,age) VALUES ('Matthew',33);
INSERT INTO customer_info (name,age) VALUES ('Abraham',54);
INSERT INTO customer_info (name,age) VALUES ('Kandake',23);
INSERT INTO customer_info (name,age) VALUES ('Ephraim',43);
INSERT INTO customer_info (name,age) VALUES ('Anahi',27);
INSERT INTO customer_info (name,age) VALUES ('Leah',67);
INSERT INTO customer_info (name,age) VALUES ('Shawn',29);

INSERT INTO books (author,title,genre,user_id) VALUES ('JR Tolkien','The Hobbit','Fantasy',1);
INSERT INTO books (author,title,genre,user_id) VALUES ('JK Rowling','Harry Potter','Adventure',2);
INSERT INTO books (author,title,genre,user_id) VALUES ('CS Lewis','Witch and Wardrobe','Adventure',3);
INSERT INTO books (author,title,genre,user_id) VALUES ('Dan Brown','Da Vinci Code','Mystery',4);
INSERT INTO books (author,title,genre,user_id) VALUES ('Paulo Coehlo','The Alchemist','Fantasy',5);
INSERT INTO books (author,title,genre,user_id) VALUES ('JD Salinger','Catcher in the Rye','Coming of Age',6);
INSERT INTO books (author,title,genre,user_id) VALUES ('Harper Lee','To Kill A Mockingbird','Literature',7);
INSERT INTO books (author,title,genre,user_id) VALUES ('VC Andrews','Flowers in the Attic','Literature',8);
INSERT INTO books (author,title,genre,user_id) VALUES ('Leo Tolstoy','War and Peace','Literature',9);
INSERT INTO books (author,title,genre,user_id) VALUES ('Jeffrey Archer','Kane and Abel','Literature',10);
INSERT INTO books (author,title,genre,user_id) VALUES ('Scott Fitzgerald','Great Gatsby','Literature',11);
INSERT INTO books (author,title,genre,user_id) VALUES ('Elbert Hubbard','Message to Garcia','Literature',12);
INSERT INTO books (author,title,genre,user_id) VALUES ('Jane Austen','Pride and Prejudice', 'Literature',13);
INSERT INTO books (author,title,genre,user_id) VALUES ('Roald Dahl','Charlie and Chocolate Factory','Entertainment',14);
INSERT INTO books (author,title,genre,user_id) VALUES ('Dr.Seuss','Cat in the Hat','Childrens',15);